config/routes.rb
Events::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'

  namespace :admin do
    resources :events
    resources :categories
    resources :users
  end

  

end

app/models/event.rb
class Event < ActiveRecord::Base

  validates :title, presence: true, length: { minimum: 5 }
  validates :brief_description, presence: true, length: { minimum: 5 }
  validates :address, :presence => true, length: { :minimum => 5 }

  mount_uploader :image, ImageUploader

  private

	def start_date_is_date?
   		if !start_date.is_a?(Date)
     		errors.add(:start_date, 'must be a valid date') 
   		end
  	end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

before_filter do
    resource = controller_path.singularize.gsub('/', '_').to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

  before_filter :authenticate_user!
  #load_and_authorize_resource except: [:create]

	def index
		@events = Event.all
	end

	def new
		@event = Event.new
	end

	def create
		 @event = Event.new(event_params)

	    respond_to do |format|
	      if @event.save
	        @events = Event.all
	        format.html { render action: 'index', notice: 'Event was successfully created.' }
	        format.json { render action: 'show', status: :created, location: @event }
	      else
	        format.html { render action: 'new' }
	        format.json { render json: @event.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		if @event.update_attributes(event_params)
        	redirect_to :action => 'show', :id => @event
      	else
        	render :action => 'edit'
    	end
	end

	def show
		@event = Event.find(params[:id])
	end

	def destroy
		Event.find(params[:id]).destroy
      	redirect_to :action => 'index'
	end

	def event_params
      params.require(:event).permit(:title, :brief_description, :start_date, :end_date, :time_start, :time_end, :address, :long_description, :image, :website_url, :image_cache)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/edit.html.erb
<h2>Edit Event</h2>

<%= form_for :event, :html => {:multipart => true}, url: admin_events_path do |f| %>
 


  <div class="form-group">
    <label for="title">Title</label>
    <%= f.text_field :title, { :class => "form-control", :placeholder => "Event Title" } %>
  </div>
  <div class="form-group">
    <label for="brief_description">Brief Description</label>
    <%= f.text_field :brief_description, { :class => "form-control", :placeholder => "Brief Description" } %>
  </div>
  <div class="form-group">
    <label for="image">Event Image</label>
    <%= image_tag(@event.image_url) if @event.image? %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>   
  </div>
  <button type="submit" class="btn btn-default btn-primary">Submit</button>



<% if @event.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited
      this event from being saved:</h2>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>


	
<% end %>

app/views/admin/events/index.html.erb
<h3>All events<%= link_to 'New Event', new_admin_event_path, { :class => "btn btn-primary pull-right" }%></h3>



<table class="table table-bordered table-striped">
	<tr>
		<th>Id</th>
		<th>Title</th>
		<th>Brief Description</th>
		<th>Image</th>
		<th>&nbsp;</th>
	</tr>
	<% @events.each do |event| %>
	<tr>
		<td><%= event.id %></td>
		<td><%= event.title %></td>
		<td><%= event.brief_description %></td>
		<td><img class="img-responsive" src="<%= event.image_url %>"/></td>
		<td><%= link_to 'Edit', edit_admin_event_path(event.id) %> | <%= link_to 'Delete', admin_event_path(event.id), data: { confirm: 'Are you sure you want to delete this event?' }, :method => :delete %></td>
	</tr>
	<% end %>
</table>

app/views/admin/events/new.html.erb
<%= link_to 'All Events', admin_events_path, { :class => "btn btn-default" } %>

<h1>New Event</h1>


<%= form_for :event, :html => {:multipart => true, :class => "form-horizontal" }, url: admin_events_path do |f| %>
 
  <div class="form-group">
    <label for="title" class="col-lg-2 control-label">Title</label>
    <div class="col-lg-4">
      <%= f.text_field :title, { :class => "form-control", :placeholder => "Event Title" } %>
    </div>
  </div>
  <div class="form-group">
    <label for="brief_description" class="col-lg-2 control-label">Brief Description</label>
    <div class="col-lg-4">
      <%= f.text_field :brief_description, { :class => "form-control", :placeholder => "Brief Description" } %>
    </div>
  </div>
  <div class="form-group">
    <label for="start_date" class="col-lg-2 control-label">Start Date</label>
    <div class=' col-lg-2' id='datetimepicker1'>
      <%= f.text_field :start_date, { :class => "form-control", :placeholder => "Start Date" } %>
      
    </div>
  </div>
  <div class="form-group">
    <label for="end_date" class="col-lg-2 control-label">End Date</label>
    <div class='  col-lg-2' id='datetimepicker1'>
      <%= f.text_field :end_date, { :class => "form-control ", :data_format => "yyyy-MM-dd", :placeholder => "End Date" } %>
      
    </div>
  </div>
  <div class="form-group">
    <label for="time_start" class="col-lg-2 control-label">Start Time</label>
    <div class='col-lg-2' id='datetimepicker4'>
      <%= f.text_field :time_start, { :class => "form-control", :placeholder => "Start Time" } %>
      
    </div>
  </div>
  <div class="form-group">
    <label for="time_end" class="col-lg-2 control-label">End Time</label>
    <div class='  col-lg-2' id='datetimepicker4'>
      <%= f.text_field :time_end, { :class => "form-control", :data_format => "HH:mm", :placeholder => "End Time" } %>
      
    </div>
  </div>
  <div class="form-group">
    <label for="address" class="col-lg-2 control-label">Address</label>
    <div class="col-lg-4">
      <%= f.text_field :address, { :class => "form-control", :placeholder => "Address" } %>
    </div>
  </div>
  <div class="form-group">
    <label for="long_description" class="col-lg-2 control-label">Long Description</label>
    <div class="col-lg-4">
      <%= f.text_area :long_description, { :class => "form-control", :placeholder => "Long Description" } %>
    </div>
  </div>
  <div class="form-group">
    <label for="image" class="col-lg-2 control-label">Event Image</label>
    <div class="col-lg-4">
      <%= image_tag(@event.image_url, { :class => 'img-responsive'}) if @event.image? %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>   
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <button type="submit" class="btn btn-default btn-primary">Create</button>
    </div>
  </div>



  



<% if @event.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited
      this event from being saved:</h2>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>


	
<% end %>