config/routes.rb
Events::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'

  namespace :admin do
    resources :events
    resources :categories
    resources :users
  end

  

end

app/models/category.rb
class Category < ActiveRecord::Base

  validates :name, presence: true, length: { minimum: 5 }, :uniqueness => true

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  before_action :login_required, except: [:index, :show]
  before_action :role_required,  except: [:index, :show]

  before_filter :authenticate_user!
  #load_and_authorize_resource
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        @categories = Category.all
        format.html { render action: 'index', notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        @categories = Category.all
        format.html { render action: 'index', notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category], :html => {:multipart => true, :class => "form-horizontal" }) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation" class="panel panel-danger">
      <div class="panel-heading">Validation errors occurred</div>
      <div class="panel-body">
      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
      </div>
    </div>
  <% end %>
<div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Category</label>
    <div class="col-sm-10">
      <%= f.text_field :name, { :class => "form-control", :placeholder => "Category name" } %>
    </div>
  </div>
    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <button type="submit" class="btn btn-default btn-primary">Save</button>
      </div>
    </div>

<% end %>

app/views/admin/categories/edit.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <h3>Edit Category <%=link_to 'All Categories', admin_categories_path, :class=> "btn btn-primary pull-right" %></h3>
    <hr/>
    <%=render 'form' %>
  </div>

app/views/admin/categories/index.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <h3>
      All Categories <%=link_to 'New Category', new_admin_category_path, :class=>        "btn btn-primary pull-right" %>
    </h3>
    <table class="table table-responsive table-striped">
      <thead>
        <tr>
          <th>
            Name
          </th>
          <th>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td>
              <%=category.name %>
            </td>
            <td>
              <%=link_to 'Edit', edit_admin_category_path(category), :class=>
                "btn btn-primary btn-sm" %>
                <%=link_to 'Destroy', [:admin, category], method: :delete, data: { confirm:
                'Are you sure?' }, :class=>
                  "btn btn-danger btn-sm" %>
            </td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

app/views/admin/categories/new.html.erb
<div class="row">
<div class="col-lg-8 col-lg-offset-2">
  <h3>New Category <%= link_to 'All Categories', admin_categories_path, :class => "btn btn-primary pull-right" %></h3>
  <hr/>
<%= render 'form' %>

</div>

app/views/admin/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>