config/routes.rb
Events::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'

  namespace :admin do
    resources :events
    resources :categories
    resources :users
  end

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Events</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= yield :stylesheets %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield :role_sidebar%>
<%== yield :role_main%>
<div class="container">
  <nav class="navbar navbar-default navbar-inverse" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Events</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        
        <li><%= nav_link "Users", admin_users_path %></li>
        
        <li><%= nav_link "Events", admin_events_path %></li>
        <li><%= nav_link "Categories", admin_categories_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Sign up", new_user_registration_path, :class => '' %></li>
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
        <% end %>

      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </nav>


  <div class="container">
    <% render "shared/flash" %>

    <%= yield %>
  </div>
</div>
</body>
</html>